# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "ko-KR"
name: "SY Choi"
logo: "/assets/images/logo.png"
title: 지식을 통해 지혜를 얻는다
subtitle: Sapientia Per Scientiam
email: chsy0823@gmail.com
description: >- 
   지식과 실패의 기록을 통해 지혜를 배우고, 그 지혜로 세상의 어두운 곳을 밝히는 기술을 개발하는 과정을 남긴다.
   여기서의 모든 학습과 탐구는 나를 단련시키고, 혁신적인 기술로 세상에 긍정적인 영향을 끼치기 위한 수련의 장이다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chsy0823.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: chsy0823
repository: chsy0823/chsy0823.github.io
# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-category-pages
  - jekyll-sitemap
  - jekyll-include-cache

minimal_mistakes_skin: "dark" 
teaser: "/assets/images/teaser.jpg"
breadcrumbs: true
show_date: true
search: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
author:
  name: "SY Choi (Elon)"
  avatar: "/assets/images/avatar.jpg"
  bio: "degree of Master of Science in Computer & Information Communication Engineering"
  location: "Seoul, Korea"
  github: "chsy0823"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:chsy0823@gmail.com"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

include:
  - _pages
  - .htaccess

# Analytics
analytics:
  provider               : google-gtag # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : G-J63Y8EDP27
    anonymize_ip         : # true, false (default)

google_site_verification: 9-cUW-VAhSn2wCPCbGRdyEcjXQJst2-L5nmUxJZEvmk
comments:
  provider: utterances
  utterances:
    theme                : "github-dark"
    issue_term           : "url" 
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
